-- Setting up the database
BetterBlizzPlatesDB = BetterBlizzPlatesDB or {}
BBP = BBP or {}

local nahjAuraWhitelist = {
    {
        ["flags"] = {
            ["pandemic"] = false,
            ["important"] = true,
        },
        ["comment"] = "",
        ["id"] = 102351,
        ["entryColors"] = {
            ["text"] = {
                ["a"] = 1,
                ["r"] = 0,
                ["g"] = 1,
                ["b"] = 0,
            },
        },
        ["name"] = "",
    }, -- [1]
}

local function updateAuraList(nahjList, userList)
    for _, newEntry in ipairs(nahjList) do
        local isEntryExists = false
        local entryId = newEntry.id or ""
        local entryName = newEntry.name or ""

        for _, existingEntry in ipairs(userList) do
            local existingId = existingEntry.id or ""
            local existingName = existingEntry.name or ""

            if (entryId ~= "" and entryId == existingId) or (entryName ~= "" and entryName == existingName) then
                isEntryExists = true
                break
            end
        end

        if not isEntryExists then
            local entryToAdd = {}
            if entryName ~= "" then
                entryToAdd.name = entryName
            else
                entryToAdd.id = entryId
                entryToAdd.name = ""
            end
            entryToAdd.entryColors = newEntry.entryColors
            entryToAdd.flags = newEntry.flags
            entryToAdd.comment = newEntry.comment or ""
            table.insert(userList, entryToAdd)
        end
    end
end

function BBP.NahjProfile()
    updateAuraList(nahjAuraWhitelist, BetterBlizzPlatesDB.auraWhitelist)

    local db = BetterBlizzPlatesDB
	db.nameplateAuraTaller = false
	db.totemIndicatorScale = 1.299999952316284
	db.NamePlateClassificationScale = "1.25"
	db.defaultLargeNamePlateFont = "Fonts\\FRIZQT__.TTF"
	db.executeIndicatorAnchor = "LEFT"
	db.arenaIdYPos = 0
	db.nameplateFriendlyWidthScale = 60
	db.nameplatePlayerLargerScale = "1.8"
	db.nameplateDefaultFriendlyHeight = 45
	db.friendlyNpBuffFilterLessMinite = false
	db.otherNpdeBuffFilterWatchList = true
	db.castBarRecolorInterrupt = false
	db.customTextureFriendly = "Dragonflight (BBP)"
	db.classIndicatorXPos = 0
	db.colorNPCName = false
	db.absorbIndicatorYPos = 0
	db.targetIndicatorYPos = 0
	db.friendlyNpBuffFilterAll = false
	db.focusTargetIndicatorTexture = "Shattered DF (BBP)"
	db.personalNpdeBuffEnable = false
	db.nameplateDefaultEnemyHeight = 45
	db.otherNpBuffFilterWatchList = true
	db.castbarEventsOn = true
	db.targetIndicatorScale = 1
	db.showNameplateCastbarTimer = true
	db.partyIndicatorModeOff = false
	db.questIndicatorAnchor = "LEFT"
	db.otherNpdeBuffPandemicGlow = false
	db.otherNpdeBuffEnable = false
	db.castBarShieldAnchor = "LEFT"
	db.otherNpBuffBlueBorder = false
	db.combatIndicatorXPos = 0
	db.friendlyNpdeBuffFilterWatchList = false
	db.nameplateMinAlpha = "0.6"
	db.classIndicatorScale = 1
	db.focusTargetIndicatorColorNameplate = false
	db.reopenOptions = false
	db.hasSaved = true
	db.nameplateAuraWidthGap = 4
	db.otherNpdeBuffFilterBlizzard = true
	db.arenaIdAnchor = "TOP"
	db.NamePlateVerticalScale = 2.799999952316284
	db.castBarDragonflightShield = true
	db.focusTargetIndicatorTestMode = false
	db.targetIndicatorTestMode = false
	db.absorbIndicator = true
	db.arenaIndicatorModeOff = false
	db.friendlyNpBuffBlueBorder = false
	db.arenaIndicatorModeFour = true
	db.nameplateAuraSquare = false
	db.castBarEmphasisSparkHeight = 35
	db.nameplateEnemyHeight = 50
	db.nameplateAurasYPos = 0
	db.castBarEmphasisColor = false
	db.defaultNamePlateFont = "Fonts\\FRIZQT__.TTF"
	db.customFontSize = 12
	db.nameplateAurasCenteredAnchor = false
	db.questIndicatorYPos = 0
	db.friendlyNpBuffPurgeGlow = false
	db.arenaIdXPos = 0
	db.castBarShieldYPos = 0
	db.arenaIndicatorModeThree = false
	db.nameplateDefaultLargeEnemyHeight = 64.125
	db.castBarTextScale = 1
	db.otherNpdeBuffFilterAll = false
	db.colorNPC = false
	db.classIndicatorAnchor = "TOP"
	db.focusTargetIndicatorScale = 1
	db.questIndicator = false
	db.executeIndicatorXPos = 0
	db.showNameplateTargetText = false
	db.partySpecScale = 1
	db.personalNpdeBuffFilterLessMinite = false
	db.friendlyNpdeBuffFilterAll = false
	db.partyIDScale = 1
	db.totemIndicatorHideNameAndShiftIconDown = false
	db.petIndicator = true
	db.enemyNameplateHealthbarHeight = 10.8
	db.customFont = "Yanone (BBP)"
	db.defaultLargeNamePlateFontFlags = ""
	db.personalNpBuffEnable = true
	db.nameplateAuraRelativeAnchor = "TOPLEFT"
	db.combatIndicatorEnemyOnly = true
	db.totemIndicatorAnchor = "TOP"
	db.healerIndicatorYPos = 0
	db.totemIndicatorYPos = 0
	db.nameplateLargerScale = "1.1"
	db.defaultNamePlateFontFlags = ""
	db.fadeOutNPCsAlpha = 0.2
	db.castBarRecolor = false
	db.combatIndicator = true
	db.nameplateMaxAlpha = "1.0"
	db.useCustomFont = false
	db.otherNpdeBuffFilterLessMinite = false
	db.classIndicatorYPos = 0
	db.defaultFontSize = 9
	db.combatIndicatorAnchor = "CENTER"
	db.nameplateAuraHeightGap = 4
	db.hideNPC = false
	db.nameplateHorizontalScale = "1.4"
	db.healerIndicatorEnemyOnly = false
	db.executeIndicatorFriendly = false
	db.hideNameplateAuras = false
	db.combatIndicatorPlayersOnly = true
	db.friendlyNameColor = false
	db.arenaModeSettingKey = "4: Replace name with spec + ID on top"
	db.arenaSpecScale = 1
	db.combatIndicatorArenaOnly = true
	db.nameplateOverlapH = "0.8"
	db.focusTargetIndicatorYPos = 0
	db.castBarEmphasisText = false
	db.nameplateFriendlyWidth = 60
	db.petIndicatorScale = 1
	db.personalNpdeBuffFilterAll = false
	db.totemIndicatorTestMode = false
	db.friendlyHideHealthBarNpc = true
	db.totemIndicatorGlowOff = false
	db.nameplateAuraScale = 1
	db.executeIndicatorThreshold = 40
	db.totemIndicatorScaleUpImportant = true
	db.combatIndicatorScale = 1
	db.personalNpBuffFilterAll = false
	db.partyModeSettingKey = "2: Arena ID on top of name"
	db.hideTargetHighlight = true
	db.focusTargetIndicatorXPos = 0
	db.partyIndicatorModeFour = false
	db.arenaSpecXPos = 0
	db.friendlyNpdeBuffEnable = false
	db.arenaIndicatorModeFive = false
	db.combatIndicatorYPos = 0
	db.enableCastbarEmphasis = false
	db.healerIndicator = false
	db.shortArenaSpecName = true
	db.classColorPersonalNameplate = true
	db.fadeOutNPC = false
	db.otherNpdeBuffFilterOnlyMe = false
	db.arenaIndicatorTestMode = false
	db.nameplateDefaultLargeFriendlyWidth = 154
	db.personalNpdeBuffFilterWatchList = true
	db.castBarShieldXPos = 0
	db.castBarEmphasisIcon = false
	db.healerIndicatorAnchor = "TOPRIGHT"
	db.executeIndicatorShowDecimal = true
	db.castBarEmphasisIconScale = 2
	db.partyIndicatorModeOne = false
	db.totemIndicatorEnemyOnly = true
	db.testAllEnabledFeatures = false
	db.questIndicatorXPos = 0
	db.castBarEmphasisHealthbarColor = false
	db.healerIndicatorXPos = 0
	db.enemyNameScale = 1
	db.castBarIconXPos = 0
	db.nameplateOccludedAlphaMult = "0.4"
	db.absorbIndicatorTestMode = false
	db.classIconColorBorder = true
	db.wasOnLoadingScreen = false
	db.executeIndicatorNotOnFullHp = false
	db.focusTargetIndicatorAnchor = "TOPRIGHT"
	db.removeRealmNames = true
	db.nameplateMinScale = "1"
	db.raidmarkIndicatorScale = 1
	db.nameplateDefaultFriendlyWidth = 110
	db.nameplateResourceScale = 0.7
	db.petIndicatorYPos = 0
	db.healerIndicatorTestMode = false
	db.classIndicator = false
	db.nameplateEnemyWidth = 135
	db.castBarEmphasisHeightValue = 24
	db.partyIndicatorModeTwo = true
	db.nameplateAurasXPos = 0
	db.totemIndicator = true
	db.absorbIndicatorOnPlayersOnly = true
	db.arenaSpecAnchor = "TOP"
	db.executeIndicatorScale = 1
	db.raidmarkIndicatorXPos = 0
	db.healerIndicatorScale = 1
	db.castBarEmphasisOnlyInterruptable = false
	db.nameplateAuraRowAmount = 5
	db.raidmarkIndicatorYPos = 0
	db.executeIndicatorYPos = 0
	db.otherNpBuffFilterLessMinite = false
	db.executeIndicator = false
	db.combatIndicatorSap = true
	db.nameplateMaxScale = "1.1"
	db.defaultLargeFontSize = 12
	db.NamePlateVerticalScaleScale = 2.799999952316284
	db.nameplateDefaultLargeEnemyWidth = 154
	db.showCastbarIfTarget = false
	db.targetIndicatorXPos = 0
	db.nameplateSelectedScale = "1.25"
	db.enemyClassColorName = true
	db.raidmarkIndicatorAnchor = "TOP"
	db.showCastBarIconWhenNoninterruptible = false
	db.totemIndicatorXPos = 0
	db.questIndicatorScale = 1
	db.absorbIndicatorXPos = 0
	db.partyIndicatorModeFive = false
	db.enableCastbarCustomization = false
	db.nameplateMotionSpeed = "0.05"
	db.targetIndicator = true
	db.friendlyNpBuffFilterWatchList = false
	db.absorbIndicatorEnemyOnly = false
	db.otherNpBuffEnable = true
	db.nameplateDefaultLargeFriendlyHeight = 64.125
	db.castBarIconScale = 1
	db.nameplateFriendlyHeight = 60
	db.raidmarkIndicator = false
	db.nameplateMinAlphaDistance = "10"
	db.castBarHeight = 18.8
	db.arenaIndicatorModeTwo = false
	db.nameplateOverlapV = "0.3"
	db.nameplateEnemyWidthScale = 135
	db.executeIndicatorAlwaysOn = false
	db.castBarEmphasisHeight = false
	db.useCustomTextureForBars = false
	db.hideDefaultPersonalNameplateAuras = false
	db.classIndicatorFriendly = true
	db.arenaIDScale = 1
	db.focusTargetIndicator = false
	db.castBarIconYPos = 0
	db.personalNpBuffFilterWatchList = true
	db.executeIndicatorTestMode = false
	db.arenaSpecYPos = 0
	db.friendlyNpdeBuffFilterOnlyMe = false
	db.nameplateDefaultEnemyWidth = 110
	db.friendlyNpdeBuffFilterLessMinite = false
	db.otherNpBuffFilterAll = false
	db.partyIndicatorModeThree = false
	db.castBarShieldScale = 1
	db.otherNpBuffPurgeGlow = false
	db.friendlyNpBuffEnable = false
	db.enableNameplateAuraCustomisation = true
	db.petIndicatorXPos = 0
	db.petIndicatorAnchor = "CENTER"
	db.friendlyNameScale = 1
	db.petIndicatorTestMode = false
	db.customTexture = "Dragonflight (BBP)"
	db.classIndicatorEnemy = true
	db.personalNpBuffFilterBlizzard = true
	db.questIndicatorTestMode = false
	db.friendlyNpBuffEmphasisedBorder = false
	db.friendlyNpBuffFilterOnlyMe = false
	db.personalNpBuffFilterLessMinite = false
	db.nameplateGlobalScale = "1.0"
	db.nameplateAuraAnchor = "BOTTOMLEFT"
	db.largeNameplates = true
	db.absorbIndicatorAnchor = "LEFT"
	db.castBarEmphasisTextScale = 2
	db.nameplateMaxAlphaDistance = "40"
	db.nameplateAurasNoNameYPos = 0
	db.hideNPCArenaOnly = false
	db.otherNpBuffEmphasisedBorder = false
	db.castBarIconAnchor = "LEFT"
	db.targetIndicatorAnchor = "TOP"
	db.totemIndicatorScaleScale = 1.299999952316284
	db.friendlyClassColorName = true
	db.friendlyNpdeBuffFilterBlizzard = false
	db.arenaIndicatorModeOne = false
	db.nameplateAuraRowAbove = true
	db.absorbIndicatorScale = 1
	db.maxAurasOnNameplate = 12
	db.friendlyNameplatesOnlyInArena = true
	db.friendlyNameplateClickthrough = true
	db.hideNPCWhitelistOn = false
end